### ISSUE TITLE
Hardcoded path to lspci

### ISSUE THREAD

**Issue by jw2dotorg** [kumina/fact-pci_devices#1]
Great script, but the path on RHEL systems is /sbin/lspci, and the script assumes /usr/bin/lspci.   I'm no ruby expert, but I'd suggest setting a variable that the user can set, or some logic to try to search some "usual" places.

 19 if FileTest.exists?("/usr/bin/lspci")
 ...
 30   %x{/usr/bin/lspci -v -mm -k}.each_line do |line|

**Comment by pieterlexis** [comment]
Hi, 

I put in support for Redhat based distro's in the branch redhat_support. I have no redhat machines available. Could you test the code and tell me it works?

**Comment by jw2dotorg** [comment]
Results on a RHEL6 box:

```
$ FACTERLIB=/var/lib/puppet/lib/facter facter 
    /var/lib/puppet/lib/facter/pci_devices.rb:30:in `exists?': can't convert nil into String (TypeError)
from /var/lib/puppet/lib/facter/pci_devices.rb:30
from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:73:in `load'
from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:73:in `load_file'
from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:38:in `load_all'
from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:33:in `each'
from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:33:in `load_all'
from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:30:in `each'
from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:30:in `load_all'
from /usr/lib/ruby/site_ruby/1.8/facter/util/collection.rb:90:in `load_all'
from /usr/lib/ruby/site_ruby/1.8/facter.rb:95:in `to_hash'
from /usr/bin/facter:137
$ rpm -qv ruby
ruby-1.8.7.299-7.el6.x86_64
$ rpm -qv facter
facter-1.5.8-1.el6.noarch
```

**Comment by pieterlexis** [comment]
It appears that it isn't "Redhat" but "RedHat", that is fixed now (along with some error handling). Let me know if it works.

**Comment by jw2dotorg** [comment]
Seems to work just fine now.  

I haven't looked closely at the docs for lspci, but in addition to Vendor and Device, it also returns SVendor and SDevice, with different information -- sometimes better information -- which was the case for the HP raid controller I was interested in below:

```
$ FACTERLIB=/var/lib/puppet/lib/facter facter | egrep '(ethernet|fibre|raid)'
ethernetcontroller0_device => OneConnect 10Gb NIC
ethernetcontroller0_driver => be2net
ethernetcontroller0_vendor => Emulex Corporation
ethernetcontroller1_device => OneConnect 10Gb NIC
ethernetcontroller1_driver => be2net
ethernetcontroller1_vendor => Emulex Corporation
fibrechannel0_device => Zephyr-X LightPulse Fibre Channel Host Adapter
fibrechannel0_driver => lpfc
fibrechannel0_vendor => Emulex Corporation
fibrechannel1_device => Zephyr-X LightPulse Fibre Channel Host Adapter
fibrechannel1_driver => lpfc
fibrechannel1_vendor => Emulex Corporation
raidcontroller0_driver => hpsa
raidcontroller0_sdevice => Smart Array P410i
raidcontroller0_svendor => Hewlett-Packard Company
```

Obviously, it was easy to adjust the code to pull SDevice, but just wanted to mention it.

**Comment by pieterlexis** [comment]
Alright, that's great! Merged the branch into master.
